name: firefly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # Firebase Essentials
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # State Management & Utilities
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Package to generate the App Icon automatically
  flutter_launcher_icons: ^0.13.1

# Configuration for the App Icon Generator
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000" # Matches your dark theme
  adaptive_icon_foreground: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  # Enable assets to use images inside the app (Login Screen, etc.)
  assets:
    - assets/icon/